/*

               ssSearch.js              
 Authors: Martin Holmes and Joey Takeda.
 mholmes@uvic.ca, joey.takeda@gmail.com.
       University of Victoria.          

 This file is part of the projectEndings staticSearch
 project. 

 Free to anyone for any purpose, but acknowledgement 
 would be appreciated. The code is licensed under 
 both MPL and BSD.

 WARNING:
 This lib has "use strict" defined. You may
 need to remove that if you are mixing this
 code with non-strict JavaScript.
*/
'use strict';const PHRASE=0,MUST_CONTAIN=1,MUST_NOT_CONTAIN=2,MAY_CONTAIN=3,WILDCARD=4,arrTermTypes=[PHRASE,MUST_CONTAIN,MUST_NOT_CONTAIN,MAY_CONTAIN,WILDCARD],TO_GET=0,GETTING=1,GOT=2,FAILED=3;var ss={};ss.captions=new Map;ss.captions.set("en",{});ss.captions.get("en").strLoading="Loading...";ss.captions.get("en").strSearching="Searching...";ss.captions.get("en").strDocumentsFound="Documents found: ";ss.captions.get("en")[PHRASE]="Exact phrase: ";ss.captions.get("en")[MUST_CONTAIN]="Must contain: ";
ss.captions.get("en")[MUST_NOT_CONTAIN]="Must not contain: ";ss.captions.get("en")[MAY_CONTAIN]="May contain: ";ss.captions.get("en")[WILDCARD]="Wildcard term: ";ss.captions.get("en").strScore="Score: ";ss.captions.get("en").strSearchTooBroad="Your search is too broad. Include more letters in every term.";ss.captions.get("en").strDiscardedTerms="Not searched (too common or too short): ";ss.captions.get("en").strShowMore="Show more";ss.captions.get("en").strShowAll="Show all";
ss.captions.get("en").strTooManyResults="Your search returned too many results. Include more filters or more search terms.";ss.captions.set("fr",{});ss.captions.get("fr").strLoading="Chargement en cours...";ss.captions.get("fr").strSearching="Recherche en cours...";ss.captions.get("fr").strDocumentsFound="Documents localisés: ";ss.captions.get("fr")[PHRASE]="Phrase exacte: ";ss.captions.get("fr")[MUST_CONTAIN]="Doit contenir: ";ss.captions.get("fr")[MUST_NOT_CONTAIN]="Ne doit pas contenir: ";
ss.captions.get("fr")[MAY_CONTAIN]="Peut contenir: ";ss.captions.get("fr")[WILDCARD]="Caractère générique: ";ss.captions.get("fr").strScore="Score: ";ss.captions.get("fr").strSearchTooBroad="Votre recherche est trop large. Inclure plus de lettres dans chaque terme.";ss.captions.get("fr").strDiscardedTerms="Recherche inaboutie (termes trop fréquents ou trop brefs): ";ss.captions.get("fr").strShowMore="Montrez plus";ss.captions.get("fr").strShowAll="Montrez tout";
ss.captions.get("fr").strTooManyResults="Votre recherche a obtenu trop de résultats. Il faut inclure plus de filtres ou plus de termes de recherche.";ss.captions.set("de",{});ss.captions.get("de").strLoading="lädt…";ss.captions.get("de").strSearching="sucht…";ss.captions.get("de").strDocumentsFound="Treffer: ";ss.captions.get("de")[PHRASE]="Exakte Formulierung: ";ss.captions.get("de")[MUST_CONTAIN]="Muss enthalten: ";ss.captions.get("de")[MUST_NOT_CONTAIN]="Darf nicht enthalten: ";
ss.captions.get("de")[MAY_CONTAIN]="Kann enthalten: ";ss.captions.get("de")[WILDCARD]="Platzhalter: ";ss.captions.get("de").strScore="Rating: ";ss.captions.get("de").strSearchTooBroad="Die Suche ergibt zu viele Treffer. Bitte die Zeichenzahl im Wort erhöhen.";ss.captions.get("de").strDiscardedTerms="Nicht gesucht (zu kurz oder zu allgemein): ";ss.captions.get("de").strShowMore="Mehr";ss.captions.get("de").strShowAll="Zeige alles";ss.captions.get("de").strTooManyResults="Die Suche ergibt zu viele Treffer. Durch Filterung oder Suchbegriffe einschränken.";
ss.stopwords="i me my myself we our ours ourselves you your yours yourself yourselves he him his himself she her hers herself it its itself they them their theirs themselves what which who whom this that these those am is are was were be been being have has had having do does did doing a an the and but if or because as until while of at by for with about against between into through during before after above below to from up down in out on off over under again further then once here there when where why how all any both each few more most other some such no nor not only own same so than too very s t can will just don should now".split(" ");
ss.debounce=(a,b)=>{let c;return function(...d){clearTimeout(c);c=setTimeout(()=>{clearTimeout(c);a(...d)},b)}};
class StaticSearch{constructor(){try{this.captions=ss.captions;this.captionLang=document.getElementsByTagName("html")[0].getAttribute("lang")||"en";this.captions.has(this.captionLang)?this.captionSet=this.captions.get(this.captionLang):this.captionSet=this.captions.get("en");this.splashMessage=document.getElementById("ssSplashMessage");null!==this.splashMessage&&(this.splashMessage.innerText=this.captionSet.strLoading,document.body.classList.add("ssLoading"));this.ssForm=document.querySelector("#ssForm");
if(!this.ssForm)throw Error("Failed to find search form. Search functionality will probably break.");this.jsonDirectory=this.ssForm.getAttribute("data-ssfolder")||"staticSearch";this.jsonDirectory+="/";this.fetchHeaders={credentials:"same-origin",cache:"default",headers:{Accept:"application/json"},method:"GET",redirect:"follow",referrer:"no-referrer"};if(this.queryBox=document.querySelector("input#ssQuery[type='text']"))this.queryBox.focus();else throw Error('Failed to find text input box with id "ssQuery". Cannot provide search functionality.');
if(this.searchButton=document.querySelector("button#ssDoSearch"))this.searchButton.addEventListener("click",function(){this.doSearch();return!1}.bind(this));else throw Error("Failed to find search button. Cannot provide search functionality.");(this.searchButton2=document.querySelector("button#ssDoSearch2"))&&this.searchButton2.addEventListener("click",function(){this.doSearch();return!1}.bind(this));(this.clearButton=document.querySelector("button#ssClear"))&&this.clearButton.addEventListener("click",
function(){this.clearSearchForm();return!1}.bind(this));this.searchingDiv=document.querySelector("div#ssSearching");if(!this.searchingDiv)throw Error('Failed to find div with id "ssSearching". Cannot provide search functionality.');this.resultsDiv=document.querySelector("div#ssResults");if(!this.resultsDiv)throw Error('Failed to find div with id "ssResults". Cannot provide search functionality.');if(this.searchInFieldset=document.querySelector(".ssSearchInFilters > fieldset"))this.searchInFieldsetName=
this.searchInFieldset.title;this.searchInFilterCheckboxes=Array.from(document.querySelectorAll("input[type='checkbox'].staticSearch_searchIn"));this.descFilterCheckboxes=Array.from(document.querySelectorAll("input[type='checkbox'].staticSearch_desc"));this.dateFilterTextboxes=Array.from(document.querySelectorAll("input[type='text'].staticSearch_date"));this.numFilterInputs=Array.from(document.querySelectorAll("input[type='number'].staticSearch_num"));this.boolFilterSelects=Array.from(document.querySelectorAll("select.staticSearch_bool"));
this.featFilterCheckboxes=[];this.featFilterInputs=Array.from(document.querySelectorAll("input[type='text'].staticSearch_feat"));for(let c of this.featFilterInputs)c.disabled=!0;this.mapFeatFilters=new Map;this.showAllBtn=this.showMoreBtn=this.paginationBtnDiv=null;this.normalizedQuery=[];this.stems=null;this.wordString="";this.mapFilterData=new Map;this.mapJsonRetrieved=new Map;this.mapActiveFilters=new Map;this.docsMatchingFilters=new XSet;this.activeContexts=new XSet;this.matchAllFilters=!1;this.getConfigInt=
function(c,d){c=parseInt(this.ssForm.getAttribute("data-"+c.toLowerCase()),10);return isNaN(c)?d:c};this.getConfigStr=function(c,d){c=this.ssForm.getAttribute("data-"+c.toLowerCase());return null!=c?c:d};this.getConfigBool=function(c,d){c=this.ssForm.getAttribute("data-"+c.toLowerCase());return/^\s*(y|Y|yes|true|True|1)\s*$/.test(c)?!0:/^\s*(n|N|no|false|False|0)\s*$/.test(c)?!1:d};this.allowPhrasal=this.getConfigBool("allowphrasal",!0);this.allowWildcards=this.getConfigBool("allowwildcards",!1);
this.scrollToTextFragment=this.getConfigBool("scrolltotextfragment",!1)&&"fragmentDirective"in document;this.kwicTruncateString=this.getConfigStr("kwictruncatestring","...");let b=this.kwicTruncateString.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");this.reKwicTruncateStr=new RegExp("(^"+b+")|("+b+"$)","g");this.downloadLimit=this.getConfigInt("downloadLimit",1E6);this.resultsLimit=this.getConfigInt("resultslimit",2E3);this.minWordLength=this.getConfigInt("minwordlength",3);this.debug=!1;this.versionString=
this.ssForm.getAttribute("data-versionString");this.index={};this.stemmer=new SSStemmer;this.terms=[];this.termLimit=this.getConfigInt("termLimit",50);this.discardedTerms=[];this.termPattern=new RegExp("^([\\*\\?\\[\\]]*[^\\*\\?\\[\\]]){"+this.minWordLength+",}[\\*\\?\\[\\]]*$");this.charsToDiscardPattern=/[\.,!;:@#$%”“\^&]/g;this.allowWildcards||(this.charsToDiscardPattern=/[\.,!;:@#$%\^&*?\[\]]/g);this.stopwords=ss.stopwords;this.jsonToRetrieve=[];this.jsonToRetrieve.push({id:"ssStopwords",path:this.jsonDirectory+
"ssStopwords"+this.versionString+".json"});this.jsonToRetrieve.push({id:"ssTitles",path:this.jsonDirectory+"ssTitles"+this.versionString+".json"});this.jsonToRetrieve.push({id:"ssWordString",path:this.jsonDirectory+"ssWordString"+this.versionString+".txt"});for(var a of document.querySelectorAll("fieldset.ssFieldset[id], fieldset.ssFieldset select[id]"))this.jsonToRetrieve.push({id:a.id,path:this.jsonDirectory+"filters/"+a.id+this.versionString+".json"});this.showSearchReport=this.isSearching=this.allJsonRetrieved=
!1;this.resultsPerPage=this.getConfigInt("resultsPerPage",0);0<this.resultsPerPage&&(this.resultItemsSelector=":scope > ul > li",this.currPage=0,this.resultItems=this.currItem=null);this.maxKwicsToShow=this.getConfigInt("maxKwicsToShow",12);this.resultSet=new SSResultSet(this.maxKwicsToShow,this.scrollToTextFragment,this.reKwicTruncateStr);window.onpopstate=function(){this.parseUrlQueryString(!0)}.bind(this);this.storeSearchesInBrowserHistory=!0;this.getJson(0);this.searchFinishedHook=function(c){};
this.parseUrlQueryString()}catch(b){console.log("ERROR: "+b.message)}}jsonRetrieved(a,b){b.match(/ssStopwords.*json$/)?(this.stopwords=a.words,this.mapJsonRetrieved.set("ssStopwords",GOT)):b.match(/ssWordString.*txt$/)?(this.wordString=a,this.mapJsonRetrieved.set("ssWordString",GOT)):b.match(/ssTitles.*json$/)?(this.resultSet.titles=new Map(Object.entries(a)),this.mapJsonRetrieved.set("ssTitles",GOT)):b.match(/\/filters\//)&&(this.mapFilterData.set(a.filterName,a),this.mapJsonRetrieved.set(a.filterId,
GOT),b.match(/ssFeat/)&&this.setupFeatFilter(a.filterId,a.filterName))}async getJson(a){if(a<this.jsonToRetrieve.length){try{if(this.mapJsonRetrieved.get(this.jsonToRetrieve[a].id)!=GOT){this.mapJsonRetrieved.set(this.jsonToRetrieve[a].id,GETTING);let b=await fetch(this.jsonToRetrieve[a].path),c=/.*\.txt$/.test(this.jsonToRetrieve[a].path)?await b.text():await b.json();this.jsonRetrieved(c,this.jsonToRetrieve[a].path)}else return this.getJson(a+1)}catch(b){console.log("ERROR: failed to retrieve resource "+
this.jsonToRetrieve[a].path+": "+b.message),this.mapJsonRetrieved.set(this.jsonToRetrieve[a].id,FAILED)}return this.getJson(a+1)}this.allJsonRetrieved=!0;document.body.classList.remove("ssLoading")}setupFeatFilter(a,b){let c=document.getElementById(a);if(null!==c)try{let d=this.mapFilterData.get(b);this.mapFeatFilters.set(b,new SSTypeAhead(c,d,b,this.minWordLength));c.querySelector("input").disabled=!1}catch(d){return console.log("ERROR: failed to set up feature filter "+a+": "+d),!1}else return console.log("ERROR: failed to find feature filter "+
a),!1}async parseUrlQueryString(a=!1){let b=new URLSearchParams(decodeURI(document.location.search)),c=!1,d=[];b.has("q")&&""!==b.get("q").trim()&&(this.queryBox.value=b.get("q"),c=!0,d.push(this.queryBox));for(var e of this.searchInFilterCheckboxes)b.has(this.searchInFieldsetName)&&-1<b.getAll(this.searchInFieldsetName).indexOf(e.value)?(c=e.checked=!0,d.push(e)):e.checked=!1;for(var g of this.descFilterCheckboxes)e=g.getAttribute("title"),b.has(e)&&-1<b.getAll(e).indexOf(g.value)?(c=g.checked=!0,
d.push(g)):g.checked=!1;for(var k of this.featFilterInputs)g=k.getAttribute("title"),e=k.parentNode.id,b.has(g)&&(c=!0,d.push(k),this.mapFeatFilters.has(g)||(e=await (await fetch(this.jsonDirectory+"filters/"+e+this.versionString+".json")).json(),this.mapFilterData.set(e.filterName,e),this.setupFeatFilter(e.filterId,e.filterName)),this.mapFeatFilters.get(g).setCheckboxes(b.getAll(g)));for(var f of this.dateFilterTextboxes)k=f.getAttribute("title")+f.id.replace(/^.+((_from)|(_to))$/,"$1"),b.has(k)&&
3<b.get(k).length?(f.value=b.get(k),c=!0,d.push(f)):f.value="";for(var h of this.numFilterInputs)f=h.getAttribute("title")+h.id.replace(/^.+((_from)|(_to))$/,"$1"),b.has(f)&&0<b.get(f).length?(h.value=b.get(f),c=!0,d.push(h)):h.value="";for(let m of this.boolFilterSelects)switch(h=m.getAttribute("title"),b.has(h)?b.get(h):""){case "true":m.selectedIndex=1;c=!0;d.push(m);break;case "false":m.selectedIndex=2;c=!0;d.push(m);break;default:m.selectedIndex=0}return!0===c?(this.openAncestorElements(d),this.doSearch(a),
!0):!1}openAncestorElements(a){let b=!1;a.forEach(function(c){for(c=c.closest("details:not([open])");null!==c;)b=c.open=!0,c=c.closest("details:not([open])")});return b}doSearch(a=!1){if(this.allowWildcards&&/[\[\]?*]/.test(this.queryBox.value)){var b=this;if(this.mapJsonRetrieved.get("ssWordString")!=GOT)return fetch(b.jsonDirectory+"ssWordString"+b.versionString+".txt",b.fetchHeaders).then(function(d){return d.text()}.bind(this)).then(function(d){b.wordString=d;b.mapJsonRetrieved.set("ssWordString",
GOT);b.doSearch()}.bind(this)).catch(function(d){console.log("Error attempting to retrieve word list: "+d)}.bind(this)),!1}this.isSearching=!0;this.setupSearchingDiv();let c=this.docsMatchingFilters.filtersActive=!1;this.discardedTerms=[];this.parseSearchQuery()?this.writeSearchReport()?(this.populateIndexes(),a||this.setQueryString(),c=!0):this.isSearching=!1:this.isSearching=!1;window.scroll({top:this.resultsDiv.offsetTop,behavior:"smooth"});return c}setupSearchingDiv(){let a=this;if(!document.body.classList.contains("ssSearching")){document.body.classList.add("ssSearching");
const b=function(){a.isSearching?window.setTimeout(b,100):document.body.classList.remove("ssSearching")};b()}}setQueryString(){try{if(1==this.storeSearchesInBrowserHistory){let a=window.location.href.split(/[?#]/)[0],b=[],c=this.queryBox.value.replace(/\s+/," ").replace(/(^\s+)|(\s+$)/g,"");0<c.length&&b.push("q="+c);for(let d of this.searchInFilterCheckboxes)d.checked&&b.push(this.searchInFieldsetName+"="+d.value);for(let d of this.descFilterCheckboxes)d.checked&&b.push(d.title+"="+d.value);this.featFilterCheckboxes=
Array.from(document.querySelectorAll("input[type='checkbox'].staticSearch_feat"));for(let d of this.featFilterCheckboxes)d.checked&&b.push(d.title+"="+d.value);for(let d of this.dateFilterTextboxes)if(d.value.match(/\d\d\d\d(-\d\d(-\d\d)?)?/)){let e=d.getAttribute("title")+d.id.replace(/^.+((_from)|(_to))$/,"$1");b.push(e+"="+d.value)}for(let d of this.numFilterInputs)if(d.value.match(/[\d\-\.]+/)){let e=d.getAttribute("title")+d.id.replace(/^.+((_from)|(_to))$/,"$1");b.push(e+"="+d.value)}for(let d of this.boolFilterSelects)0<
d.selectedIndex&&b.push(d.getAttribute("title")+"="+(1==d.selectedIndex?"true":"false"));0<b.length&&(a+="?"+encodeURI(b.join("&")),history.pushState({time:Date.now()},"",a))}return!0}catch(a){console.log("ERROR: failed to push search into browser history: "+a.message)}}parseSearchQuery(){try{var a;this.terms=[];this.normalizedQuery=[];let d=this.queryBox.value;d=d.replace(/((^\s+)|\s+$)/g,"");d=d.replace(/\s+/g," ");d=d.replace(/[‘’‛]/g,"'");d=d.replace(/(^'|'$)/g,"");if(this.allowPhrasal){d=d.replace(/""/g,
"");var b=0,c=-1;let e="";for(a=0;a<d.length;a++)e+=d.charAt(a),'"'===d.charAt(a)&&(b++,c=a);d=0<b%2?e.substr(0,c)+e.substr(c+1,e.length):e}else d=d.replace(/"/g,"");a=!1;b="";for(c=0;c<d.length;c++){let e=d.charAt(c);if('"'===e)this.addSearchItem(b,a),a=!a,b="";else if(!this.charsToDiscardPattern.test(e)||a)" "!==e||a?b+=e:(this.addSearchItem(b,!1),b="")}this.addSearchItem(b,a);this.queryBox.value=this.normalizedQuery.join(" ");this.terms.sort(function(e,g){return e.type-g.type});return!0}catch(d){return console.log("ERROR: "+
d.message),!1}}addSearchItem(a,b){if(1>a.length)return!1;if(!b&&!this.termPattern.test(a)||-1<this.stopwords.indexOf(a.toLowerCase()))return this.normalizedQuery.push(a),this.discardedTerms.push(a),!1;if(/\s/.test(a)||b){this.normalizedQuery.push('"'+a+'"');var c=a.trim().toLowerCase().split(/\s+/).map(d=>d.replaceAll(this.charsToDiscardPattern,""));for(b=0;b<=c.length&&!(0>this.stopwords.indexOf(c[b]));b++);b<c.length&&this.terms.push({str:a,stem:this.stemmer.stem(c[b]),type:PHRASE})}else if(this.normalizedQuery.push(a),
this.allowWildcards&&/[\[\]?*]/.test(a)){a=this.wildcardToRegex(a);a=[...this.wordString.matchAll(a)];for(c of a)a=this.stemmer.stem(c[1].toLowerCase()),b=c[0].replace(/[\|]/g,""),this.terms.length<this.termLimit&&(this.allowPhrasal?this.terms.push({str:b,stem:a,type:PHRASE}):this.terms.push({str:b,stem:a,type:MAY_CONTAIN}))}else/^[\+]/.test(a)?(c=a.substring(1).toLowerCase(),this.terms.push({str:a.substring(1),stem:this.stemmer.stem(c),type:MUST_CONTAIN})):/^[\-]/.test(a)?(c=a.substring(1).toLowerCase(),
this.terms.push({str:a.substring(1),stem:this.stemmer.stem(c),type:MUST_NOT_CONTAIN})):(c=a.toLowerCase(),this.terms.push({str:a,stem:this.stemmer.stem(c),type:MAY_CONTAIN}));return 0<this.terms.length}clearSearchForm(){try{this.queryBox.value="";for(let a of this.searchInFilterCheckboxes)a.checked=!1;for(let a of this.descFilterCheckboxes)a.checked=!1;this.featFilterCheckboxes=Array.from(document.querySelectorAll("input[type='checkbox'].staticSearch_feat"));for(let a of this.featFilterCheckboxes)a.checked=
!1,a.remove();for(let a of this.featFilterInputs)a.value="";this.menuFeatFilter=Array.from(document.querySelectorAll("menu div"));for(let a of this.menuFeatFilter)a.remove();this.suggestedFeatFilter=Array.from(document.querySelectorAll("div.ssSuggest span"));for(let a of this.suggestedFeatFilter)a.remove();for(let a of this.dateFilterTextboxes)a.value="";for(let a of this.numFilterInputs)a.value="";for(let a of this.boolFilterSelects)a.selectedIndex=0;return!0}catch(a){return console.log("Error attempting to clear search form: "+
a),!1}}processFilters(){try{return this.docsMatchingFilters=this.getDocIdsForFilters(),this.activeContexts=new XSet(this.searchInFilterCheckboxes.filter(a=>a.checked).map(a=>a.id)),!0}catch(a){return console.log("Error attempting to generate the set of docs matching filters: "+a),!1}}getDocIdsForFilters(){var a=[];var b=document.querySelectorAll('fieldset[id ^= "ssDesc"], fieldset[id ^="ssFeat"]');for(var c of b){b=new XSet;let m=c.getAttribute("title"),n=c.querySelectorAll('input[type="checkbox"]:checked');
if(0<n.length&&this.mapFilterData.has(m)){for(var d of n)b.addArray(this.mapFilterData.get(m)[d.id].docs);a.push(b)}}b=document.querySelectorAll('select[id ^= "ssBool"]');for(var e of b)b=e.selectedIndex,c=e.id+"_"+e.selectedIndex,d=e.getAttribute("title"),0<b&&this.mapFilterData.has(d)&&void 0!==this.mapFilterData.get(d)[c]&&(b=new XSet,b.addArray(this.mapFilterData.get(d)[c].docs),a.push(b));b=document.querySelectorAll('fieldset[id ^= "ssDate"]');for(var g of b)if(b=g.title,this.mapFilterData.has(b)){e=
this.mapFilterData.get(b).docs;c=g.querySelector('input[type="text"][id $= "_from"]').value;if(0<c.length){b=new XSet;c=new Date(c);for(var k in e)0<e[k].length&&new Date(e[k][e[k].length-1])>=c&&b.add(k);a.push(b)}c=g.querySelector('input[type="text"][id $= "_to"]').value;if(0<c.length){b=new XSet;switch(c.length){case 10:c=new Date(c);break;case 4:c=new Date(c+"-12-31");break;case 7:c=new Date(c.replace(/(\d\d\d\d-)((0[13578])|(1[02]))$/,"$1$2-31").replace(/(\d\d\d\d-)((0[469])|(11))$/,"$1$2-30").replace(/02$/,
"02-28"));break;default:c=new Date("3000")}for(const m in e)0<e[m].length&&new Date(e[m][0])<=c&&b.add(m);a.push(b)}}b=document.querySelectorAll('fieldset[id ^= "ssNum"]');for(var f of b)if(b=f.title,this.mapFilterData.has(b)){g=this.mapFilterData.get(b).docs;k=f.querySelector('input[type="number"][id $= "_from"]').value;if(0<k.length){b=new XSet;k=parseFloat(k);for(var h in g)0<g[h].length&&parseFloat(g[h][g[h].length-1])>=k&&b.add(h);a.push(b)}k=f.querySelector('input[type="number"][id $= "_to"]').value;
if(0<k.length){b=new XSet;k=parseFloat(k);for(const m in g)0<g[m].length&&parseFloat(g[m][0])<=k&&b.add(m);a.push(b)}}if(0<a.length){h=a[0];for(f=1;f<a.length;f++)h=h.xIntersection(a[f]);h.filtersActive=!0;return h}a=new XSet;a.filtersActive=!1;return a}writeSearchReport(){if(this.showSearchReport)try{var a=document.querySelector("#searchReport");a&&a.parentNode.removeChild(a);a=[];let b,c,d,e;for(b=0;b<this.terms.length;b++)a[this.terms[b].type]||(a[this.terms[b].type]={type:this.terms[b].type,terms:[]}),
a[this.terms[b].type].terms.push(`"${this.terms[b].str}" (${this.terms[b].stem})`);a.sort(function(g,k){return g.type-k.type});c=document.createElement("div");c.setAttribute("id","searchReport");a.forEach(g=>{d=document.createElement("p");e=document.createTextNode(this.captionSet[g.type]+g.terms.join(", "));d.appendChild(e);c.appendChild(d)});this.resultsDiv.parentNode.insertBefore(c,this.resultsDiv)}catch(b){return console.log("ERROR: "+b.message),!1}return!0}getTermsByType(a){let b=[];for(let c=
0;c<this.terms.length;c++)this.terms[c].type==a&&b.push(c);return b}populateIndexes(){var a,b=[],c=[],d=this;try{var e=0;for(a=this.terms.length;e<a;e++)this.index.hasOwnProperty(this.terms[e].stem)||b.push(this.terms[e].stem);var g=new Set;if(!1===this.allJsonRetrieved){for(let f of document.querySelectorAll('input[type="checkbox"].staticSearch_desc:checked, input[type="checkbox"].staticSearch_feat:checked')){let h=f.id.split("_")[0];this.mapJsonRetrieved.get(h)!=GOT&&g.add(h)}for(let f of document.querySelectorAll("select.staticSearch_bool"))if(0<
f.selectedIndex){let h=f.id.split("_")[0];this.mapJsonRetrieved.get(h)!=GOT&&g.add(h)}for(let f of document.querySelectorAll('input[type="text"].staticSearch_date'))if(3<f.value.length){let h=f.id.split("_")[0];this.mapJsonRetrieved.get(h)!=GOT&&g.add(h)}for(let f of document.querySelectorAll('input[type="number"].staticSearch_num'))if(0<f.value.length){let h=f.id.split("_")[0];this.mapJsonRetrieved.get(h)!=GOT&&g.add(h)}for(let f of g)c[c.length]=fetch(d.jsonDirectory+"filters/"+f+this.versionString+
".json",this.fetchHeaders).then(function(h){return h.json()}).then(function(h){d.mapFilterData.set(h.filterName,h);d.mapJsonRetrieved.set(h.filterId,GOT)}.bind(d)).catch(function(h){console.log("Error attempting to retrieve filter data: "+h)}.bind(d));this.mapJsonRetrieved.get("ssStopwords")!=GOT&&(c[c.length]=fetch(d.jsonDirectory+"ssStopwords"+this.versionString+".json",this.fetchHeaders).then(function(f){return f.json()}).then(function(f){d.stopwords=f.words;d.mapJsonRetrieved.set("ssStopWords",
GOT)}.bind(d)).catch(function(f){console.log("Error attempting to retrieve stopword list: "+f)}.bind(d)));this.mapJsonRetrieved.get("ssTitles")!=GOT&&(c[c.length]=fetch(d.jsonDirectory+"ssTitles"+this.versionString+".json",this.fetchHeaders).then(function(f){return f.json()}).then(function(f){d.resultSet.titles=new Map(Object.entries(f));d.mapJsonRetrieved.set("ssTitles",GOT)}.bind(d)).catch(function(f){console.log("Error attempting to retrieve title list: "+f)}.bind(d)));1==this.allowWildcards&&
this.mapJsonRetrieved.get("ssWordString")!=GOT&&(c[c.length]=fetch(d.jsonDirectory+"ssWordString"+this.versionString+".txt",this.fetchHeaders).then(function(f){return f.text()}).then(function(f){d.wordString=f;d.mapJsonRetrieved.set("ssWordString",GOT)}.bind(d)).catch(function(f){console.log("Error attempting to retrieve word string: "+f)}.bind(d)))}if(0<b.length)for(e=0,a=b.length;e<a;e++){var k={stem:b[e],instances:[]};this.stemFound(k);c[c.length]=fetch(d.jsonDirectory+"stems/"+b[e]+this.versionString+
".json",this.fetchHeaders).then(function(f){if(200<=f.status&&300>f.status&&f.headers.get("content-type")&&f.headers.get("content-type").includes("application/json"))return f.json().then(function(h){d.stemFound(h)}.bind(d))}).catch(function(f){console.log("Error attempting to retrieve "+b[e]+": "+f);return function(h){d.stemFound(h)}.bind(d,k)}.bind(d))}0<c.length?Promise.all(c).then(function(f){this.processResults()}.bind(d)):setTimeout(function(){this.processResults()}.bind(d),0)}catch(f){console.log("ERROR: "+
f.message)}}stemFound(a){try{this.index[a.stem]=a}catch(b){console.log("ERROR: "+b.message)}}indexStemHasDoc(a,b){let c=!1;if(this.index[a])for(let d=0;d<this.index[a].instances.length;d++)if(this.index[a].instances[d].docUri==b){c=!0;break}return c}clearResultsDiv(){for(;this.resultsDiv.firstChild;)this.resultsDiv.removeChild(this.resultsDiv.firstChild);return!0}reportNoResults(a){console.log("No results. Try simpler search? "+a);return!0}reportTooManyResults(){try{console.log(`Found ${this.resultSet.getSize()} results, which exceeds the ${this.resultsLimit} maximum.`);
let a=document.createElement("p");a.append(this.captionSet.strTooManyResults);this.resultsDiv.appendChild(a);return!0}catch(a){return console.log("ERROR: "+a),!1}}processResults(){try{this.resultSet.clear();this.processFilters();let b=null;if(0<this.discardedTerms.length){let l=this.captionSet.strDiscardedTerms+" "+this.discardedTerms.join(", ");b=document.createElement("p");b.classList.add("ssDiscarded");b.append(l)}if(1>this.terms.length&&1>this.docsMatchingFilters.size){this.clearResultsDiv();
null!==b&&this.resultsDiv.appendChild(b);let l=document.createElement("p");l.append(this.captionSet.strDocumentsFound+"0");this.resultsDiv.appendChild(l);this.isSearching=!1;this.searchFinishedHook(1);return!1}if(1>this.terms.length&&0<this.docsMatchingFilters.size){this.resultSet.addArray([...this.docsMatchingFilters]);this.resultSet.sortByScoreDesc();this.clearResultsDiv();null!==b&&this.resultsDiv.appendChild(b);let l=document.createElement("p");l.append(this.captionSet.strDocumentsFound+this.resultSet.getSize());
this.resultsDiv.appendChild(l);1>this.resultSet.getSize()?this.reportNoResults(!0):this.resultSet.getSize()>this.resultsLimit?this.reportTooManyResults():(this.resultsDiv.appendChild(this.resultSet.resultsAsHtml(this.captionSet.strScore)),0<this.resultsPerPage&&this.resultsPerPage<this.resultSet.getSize()&&this.paginateResults());this.isSearching=!1;this.searchFinishedHook(2);return 0<this.resultSet.getSize()}let c=this.getTermsByType(PHRASE),d=this.getTermsByType(MUST_CONTAIN),e=this.getTermsByType(MUST_NOT_CONTAIN),
g=this.getTermsByType(MAY_CONTAIN);var a=this;function k(){try{for(let l of c){let q=a.terms[l].stem,p=a.terms[l].str,r=a.phraseToRegex(p);if(a.index[q])for(let t of a.index[q].instances){let v=[];for(let u of t.contexts){let w=u.context.replace(/<[^>]+>/g,"");if(r.test(w)){let x=w.replace(r,"<mark>$&</mark>");v.push({form:p,context:x,weight:2,fid:u.fid?u.fid:"",prop:u.prop?u.prop:{},in:u.in?u.in:[]})}}0<v.length&&a.resultSet.set(t.docUri,{docUri:t.docUri,docTitle:t.docTitle,contexts:v,score:v.length})}}return!0}catch(l){return console.log("ERROR: "+
l.message),!1}}function f(){try{for(let l of e){let q=a.terms[l].stem;if(a.index[q])for(let p of a.index[q].instances)a.resultSet.has(p.docUri)&&a.resultSet.delete(p.docUri)}return!0}catch(l){return console.log("ERROR: "+l.message),!1}}function h(l,q){try{if(q){if(1>a.resultSet.getSize())return!0;for(let p of l){let r=a.terms[p].stem;if(a.index[r])for(let t of a.index[r].instances)a.resultSet.has(t.docUri)&&a.resultSet.merge(t.docUri,t)}l=[];for(let p of a.resultSet.mapDocs.keys())for(let r of d)a.indexStemHasDoc(a.terms[r].stem,
p)||l.push(p);a.resultSet.deleteArray(l)}else{let p=a.terms[0].stem;if(a.index[p])for(let r of a.index[p].instances)a.resultSet.set(r.docUri,r);h(d.slice(1),!0)}return!0}catch(p){return console.log("ERROR: "+p.message),!1}}function m(l){for(let q of g){let p=a.terms[q].stem;if(a.index[p])for(let r of a.index[p].instances)(a.resultSet.has(r.docUri)||l)&&a.resultSet.set(r.docUri,r)}}if(0<c.length)k(),f(),h(d,!0),m(!1);else if(0<d.length)h(d,!1),f(),m(!1);else if(0<g.length)m(!0),f();else return console.log("No useful search terms found."),
this.isSearching=!1,this.searchFinishedHook(3),!1;1==this.docsMatchingFilters.filtersActive&&this.resultSet.filterBySet(this.docsMatchingFilters);0<this.activeContexts.size&&this.resultSet.filterByContexts(this.activeContexts);this.resultSet.sortByScoreDesc();this.clearResultsDiv();null!==b&&this.resultsDiv.appendChild(b);let n=document.createElement("p");n.append(this.captionSet.strDocumentsFound+this.resultSet.getSize());this.resultsDiv.appendChild(n);1>this.resultSet.getSize()?this.reportNoResults(!0):
this.resultSet.getSize()>this.resultsLimit?this.reportTooManyResults():(this.resultsDiv.appendChild(this.resultSet.resultsAsHtml(this.captionSet.strScore)),0<this.resultsPerPage&&this.resultsPerPage<this.resultSet.getSize()&&this.paginateResults());this.isSearching=!1;this.searchFinishedHook(4);return 0<this.resultSet.getSize()}catch(b){return console.log("ERROR: "+b.message),this.isSearching=!1,this.searchFinishedHook(5),!1}}paginateResults(){try{return this.resultItems=this.resultsDiv.querySelectorAll(this.resultItemsSelector),
this.paginationBtnDiv=document.createElement("div"),this.paginationBtnDiv.setAttribute("id","ssPagination"),this.showMoreBtn=document.createElement("button"),this.showMoreBtn.setAttribute("id","ssShowMore"),this.showMoreBtn.innerHTML=this.captionSet.strShowMore,this.showAllBtn=document.createElement("button"),this.showAllBtn.setAttribute("id","ssShowAll"),this.showAllBtn.innerHTML=this.captionSet.strShowAll,this.paginationBtnDiv.appendChild(this.showMoreBtn),this.paginationBtnDiv.appendChild(this.showAllBtn),
this.resultsDiv.appendChild(this.paginationBtnDiv),this.showMoreResults(),this.showMoreBtn.addEventListener("click",this.showMoreResults.bind(this)),this.showAllBtn.addEventListener("click",this.showAllResults.bind(this)),!0}catch(a){return console.log("ERROR "+a.message),!1}}showAllResults(){try{return this.currItem.classList.remove("ssPaginationEnd"),this.paginationBtnDiv.style.display="none",!0}catch(a){return console.log("ERROR "+a.message),!1}}showMoreResults(){try{this.currPage++;let a=this.currPage*
this.resultsPerPage-1;null!==this.currItem&&this.currItem.classList.remove("ssPaginationEnd");if(a>=this.resultSet.getSize())return this.showAllResults(),!0;this.currItem=this.resultItems[a];this.currItem.classList.add("ssPaginationEnd");return!0}catch(a){return console.log("ERROR "+a.message),!1}}phraseToRegex(a){let b=a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&").replace(/'/g,"['‘’‛]").replace(/[“”]/g,'[“”"]');/^\w/.test(a)&&(b="\\b"+b);/\w$/.test(a)&&(b+="\\b");try{return new RegExp(b)}catch(c){return console.log("Invalid regex from phrase created: "+
b),null}}wildcardToRegex(a){if(a.match(/[\s"]]/))return null;a=a.replace(/[.+^${}()|\\]/g,"\\$&").replace(/[\?]/g,"[^\\|]").replace(/[\*]/g,"[^\\|]$&?");try{return new RegExp("\\|("+a+")\\|","gi")}catch(b){return console.log("Invalid regex created: "+a),null}}}
class SSResultSet{constructor(a,b,c){try{this.mapDocs=new Map([]),this.maxKwicsToShow=a,this.scrollToTextFragment=b,this.reKwicTruncateStr=c,this.titles=null}catch(d){console.log("ERROR: "+d.message)}}clear(){try{return this.mapDocs.clear(),!0}catch(a){return console.log("ERROR: "+a.message),!1}}addArray(a){try{for(let b of a)this.mapDocs.set(b,{docUri:b,score:0,sortKey:this.getSortKeyByDocId(b),contexts:[]});return!0}catch(b){return console.log("ERROR: "+b.message),!1}}has(a){return this.mapDocs.has(a)}set(a,
b){try{return this.mapDocs.has(a)?this.merge(a,b):(this.mapDocs.set(a,b),this.mapDocs.get(a).sortKey=this.getSortKeyByDocId(a),this.mapDocs.get(a).contexts=this.mapDocs.get(a).contexts.slice(0,this.maxKwicsToShow)),!0}catch(c){return console.log("ERROR: "+c.message),!1}}merge(a,b){try{if(this.mapDocs.has(a)){let c=this.mapDocs.get(a);for(a=0;a<b.contexts.length;)0>c.contexts.indexOf(b.contexts[a])&&(c.contexts.push(b.contexts[a]),c.score+=b.score),a++}else this.mapDocs.set(a,b),this.mapDocs.get(a).sortKey=
this.getSortKeyByDocId(a);return!0}catch(c){return console.log("ERROR: "+c.message),!1}}delete(a){try{return this.mapDocs.delete(a)}catch(b){return console.log("ERROR: "+b.message),!1}}deleteArray(a){let b=!1;try{for(let c=0;c<a.length;c++){let d=this.mapDocs.delete(a[c]);b=b||d}return b}catch(c){return console.log("ERROR: "+c.message),!1}}filterByContexts(a){try{for(let [b,c]of this.mapDocs){let d=c.contexts.filter(e=>e.hasOwnProperty("in")?0<(new XSet(e.in)).xIntersection(a).size:!1);0===d.length?
this.mapDocs.delete(b):this.mapDocs.set(b,{...c,contexts:d,score:parseInt(d.reduce((e,g)=>e+parseInt(g.weight),0))})}return 0<this.mapDocs.size}catch(b){return console.log("ERROR: "+b.message),!1}}filterBySet(a){try{for(let [b]of this.mapDocs)a.has(b)||this.mapDocs.delete(b);return 0<this.mapDocs.size}catch(b){return console.log("ERROR: "+b.message),!1}}getSize(){try{return this.mapDocs.size}catch(a){return console.log("ERROR: "+a.message),0}}getContextCount(){try{let a=[];for(let [,b]of this.mapDocs)a.push(b.contexts.length);
return a.reduce(function(b,c){return b+c},0)}catch(a){return console.log("ERROR: "+a.message),0}}sortByScoreDesc(){try{let a=this.mapDocs.size;this.mapDocs=new Map([...this.mapDocs.entries()].sort(function(b,c){let d=c[1].sortKey-b[1].sortKey;return 0==d?b[1].sortKey.localeCompare(c[1].sortKey):d}));return a===this.mapDocs.size}catch(a){return console.log("ERROR: "+a.message),!1}}resultsAsHtml(a){let b=document.createElement("ul");for(let [,f]of this.mapDocs){let h=document.createElement("li"),m=
document.createElement("div");var c=this.getTitleByDocId(f.docUri),d=c.split("ssStart");let n=document.createElement("div");n.setAttribute("class","updatedResult");d.forEach((l,q)=>{let p=document.createElement("div");p.setAttribute("class",`ssResultUpdate${q}`);l=document.createTextNode(l);p.appendChild(l);n.appendChild(p)});d=this.getThumbnailByDocId(f.docUri);if(0<d.length){var e=document.createElement("a");e.setAttribute("href",f.docUri);var g=document.createElement("img");g.setAttribute("alt",
c);g.setAttribute("title",c);g.setAttribute("src",d);e.appendChild(g);h.appendChild(e)}c=document.createElement("a");c.setAttribute("href",f.docUri);c.appendChild(n);m.appendChild(c);0<f.score&&(c=document.createElement("span"),d=document.createTextNode(" "),c.innerHTML=a+f.score,m.append(d),m.appendChild(c));if(0<f.contexts.length){f.contexts.sort(function(l,q){return l.pos-q.pos});c=document.createElement("ul");c.setAttribute("class","kwic");for(d=0;d<Math.min(f.contexts.length,this.maxKwicsToShow);d++){e=
document.createElement("li");g=document.createElement("span");g.innerHTML=f.contexts[d].context;e.appendChild(g);g=f.contexts[d].context.replace(/<\/?mark>/g,"").replace(this.reKwicTruncateStr,"");g=this.scrollToTextFragment&&1<g.length?encodeURIComponent(":~:text="+g):"";var k=f.contexts[d].context.replace(/.*<mark>([^<]+)<\/mark>.+/,"$1");k="?ssMark="+encodeURIComponent(k);if(f.contexts[d].hasOwnProperty("fid")&&""!=f.contexts[d].fid||""!=g){let l=f.contexts[d].hasOwnProperty("fid")?f.contexts[d].fid:
"",q=document.createElement("a");q.appendChild(document.createTextNode("↬"));q.setAttribute("href",f.docUri+k+"#"+l+g);q.setAttribute("class","fidLink");e.appendChild(q)}else g=document.createElement("span"),g.appendChild(document.createTextNode(" ")),e.appendChild(g);if(f.contexts[d].hasOwnProperty("prop")){g=Object.entries(f.contexts[d].prop);for(const [l,q]of g)e.setAttribute("data-ss-"+l,q),"img"==l&&(g=document.createElement("img"),g.setAttribute("src",q),e.insertBefore(g,e.firstChild))}c.appendChild(e)}m.appendChild(c)}h.appendChild(m);
b.appendChild(h)}return b}getTitleByDocId(a){try{return this.titles.get(a)[0]}catch(b){return"[No title]"}}getThumbnailByDocId(a){try{return 1<this.titles.get(a).length?this.titles.get(a)[1]:""}catch(b){return""}}getSortKeyByDocId(a){try{return 2<this.titles.get(a).length?this.titles.get(a)[2]:""}catch(b){return""}}resultsAsObject(){let a=0,b=0;for(let [,c]of this.mapDocs)a+=c.score,b+=c.contexts.length;return{docsFound:this.mapDocs.size,contextsFound:b,scoreTotal:a}}}
class XSet extends Set{constructor(a){super(a);this.filtersActive=!1}xUnion(a){return new XSet([...this,...a])}xIntersection(a){return new XSet([...this].filter(b=>a.has(b)))}xDifference(a){return new XSet([...this].filter(b=>!a.has(b)))}addArray(a){for(let b of a)this.add(b)}}
class SSTypeAhead{constructor(a,b,c,d){this.rootEl=a;this.filterData=b;this.filterName=c;this.minWordLength=d;this.reId=/^ssFeat\d+_\d+$/;this.filterMap=new Map;for(let e of Object.keys(this.filterData))this.reId.test(e)&&this.filterMap.set(this.filterData[e].name,e);this.input=this.rootEl.getElementsByTagName("input")[0];this.input.addEventListener("input",this.suggest.bind(this));this.input.addEventListener("keydown",ss.debounce(function(e){this.keyOnInput(e)}.bind(this)),500);this.input.setAttribute("autocomplete",
"off");this.rootEl.setAttribute("tabindex","0");this.rootEl.addEventListener("keydown",function(e){this.escape(e.key)}.bind(this));this.menu=document.createElement("menu");this.rootEl.appendChild(this.menu);this.checkboxes=document.createElement("div");this.checkboxes.classList.add("ssSuggest");this.rootEl.appendChild(this.checkboxes);this.rootEl.addEventListener("click",function(e){this.blurringMenu(e)}.bind(this),!0);this.populating=!1}clearSuggestions(){this.menu.innerHTML=""}escape(a){"Escape"===
a&&this.clearSuggestions()}blurringMenu(a){a.target==a.currentTarget&&this.clearSuggestions()}populate(){if(!(this.populating||this.input.value.length<this.minWordLength)){this.populating=!0;try{let c=new RegExp(this.input.value,"i"),d=document.createElement("div");this.filterMap.forEach((g,k)=>{if(k.match(c)&&this.reId.test(g)){let f=document.createElement("div");f.setAttribute("data-val",k);f.setAttribute("data-id",g);f.classList.add("select");f.appendChild(document.createTextNode(k));f.setAttribute("tabindex",
"0");f.addEventListener("click",function(h){this.select(h)}.bind(this));f.addEventListener("keydown",function(h){this.keyOnSelection(h)}.bind(this));d.appendChild(f)}});let e=d.childNodes;var a=[],b;for(b in e)1==e[b].nodeType&&a.push(e[b]);a.sort(function(g,k){return g.innerHTML==k.innerHTML?0:g.innerHTML>k.innerHTML?1:-1});for(b=0;b<a.length;++b)this.menu.appendChild(a[b])}finally{this.populating=!1}}}suggest(){this.clearSuggestions();this.populate()}keyOnInput(a){"ArrowDown"===a.key&&this.menu.firstElementChild&&
(this.menu.firstElementChild.focus(),a.preventDefault())}keyOnSelection(a){let b=a.target;switch(a.key){case "Enter":this.select(a);break;case "ArrowUp":b.previousElementSibling?b.previousElementSibling.focus():this.input.focus();break;case "ArrowDown":b.nextElementSibling?b.nextElementSibling.focus():b.parentNode.firstElementChild.focus()}a.preventDefault()}select(a){a.target.getAttribute("data-id");a=a.target.getAttribute("data-val");this.addCheckbox(a)}addCheckbox(a){let b=this.filterMap.get(a);
if(b){for(var c of this.checkboxes.querySelectorAll("input"))if(c.getAttribute("id")==b){c.checked=!0;return}c=document.createElement("span");c.setAttribute("data-val",a);var d=document.createElement("input");d.setAttribute("type","checkbox");d.setAttribute("checked","checked");d.setAttribute("title",this.filterName);d.setAttribute("value",a);d.setAttribute("class","staticSearch_feat");d.setAttribute("id",b);c.appendChild(d);d=document.createElement("label");d.setAttribute("for",b);d.appendChild(document.createTextNode(a));
c.appendChild(d);a=document.createElement("button");a.appendChild(document.createTextNode("✘"));a.addEventListener("click",function(e){this.removeCheckbox(e)}.bind(this));c.appendChild(a);this.checkboxes.appendChild(c)}}setCheckboxes(a){for(let b of this.checkboxes.querySelectorAll("input"))0>a.indexOf(b.getAttribute("value"))&&(b.checked=!1);for(let b of a)this.addCheckbox(b)}removeCheckbox(a){a.target.parentNode.parentNode.removeChild(a.target.parentNode)}}
class SSStemmer{constructor(){this.vowel="[aeiouy]";this.reVowel=new RegExp(this.vowel);this.nonVowel="[^aeiouy]";this.reNonVowel=new RegExp(this.nonVowel);this.reEndsWithShortSyllable=new RegExp(this.nonVowel+this.vowel+"[^aeiouywxY]$");this.dbl="((bb)|(dd)|(ff)|(gg)|(mm)|(nn)|(pp)|(rr)|(tt))";this.reDbl=new RegExp(this.reDbl);this.reR1R2=new RegExp("^.*?"+this.vowel+this.nonVowel+"(.*)$");this.reR1Except=/^(gener|commun|arsen)(.*)$/;this.arrStep2Seq=[[/ousness$/,/ousness$/,"ous"],[/iveness$/,/iveness$/,
"ive"],[/fulness$/,/fulness$/,"ful"],[/ization$/,/ization$/,"ize"],[/ational$/,/ational$/,"ate"],[/biliti$/,/biliti$/,"ble"],[/tional$/,/tional$/,"tion"],[/lessli$/,/lessli$/,"less"],[/ousli$/,/ousli$/,"ous"],[/fulli$/,/fulli$/,"ful"],[/iviti$/,/iviti$/,"ive"],[/entli$/,/entli$/,"ent"],[/alism$/,/alism$/,"al"],[/aliti$/,/aliti$/,"al"],[/enci$/,/enci$/,"ence"],[/anci$/,/anci$/,"ance"],[/abli$/,/abli$/,"able"],[/izer$/,/izer$/,"ize"],[/ation$/,/ation$/,"ate"],[/ator$/,/ator$/,"ate"],[/alli$/,/alli$/,
"al"],[/bli$/,/bli$/,"ble"],[/logi$/,/ogi$/,"og"],[/[cdeghkmnrt]li$/,/li$/,""]];this.arrStep3Seq=[[1,/ational$/,"ate"],[1,/tional$/,"tion"],[1,/alize$/,"al"],[1,/icate$/,"ic"],[1,/iciti$/,"ic"],[2,/ative$/,""],[1,/ical$/,"ic"],[1,/ness$/,""],[1,/ful$/,""]];this.arrStep4Seq=[[/ement$/,/ement$/],[/ment$/,/ment$/],[/ance$/,/ance$/],[/ence$/,/ence$/],[/able$/,/able$/],[/ible$/,/ible$/],[/[st]ion$/,/ion$/],[/ant$/,/ant$/],[/ent$/,/ent$/],[/ism$/,/ism$/],[/ate$/,/ate$/],[/iti$/,/iti$/],[/ous$/,/ous$/],
[/ive$/,/ive$/],[/ize$/,/ize$/],[/al$/,/al$/],[/er$/,/er$/],[/ic$/,/ic$/]];this.arrExceptions="skis skies dying lying tying idly gently ugly early only singly sky news howe atlas cosmos bias andes".split(" ");this.arrExceptionStems="ski sky die lie tie idl gentl ugli earli onli singl sky news howe atlas cosmos bias andes".split(" ");this.arrStep1aExceptions="inning outing canning herring earring proceed exceed succeed".split(" ")}stem(a){a=a.normalize("NFC");if(3>a.length)return a;var b=this.arrExceptions.indexOf(a);
if(-1<b)return this.arrExceptionStems[b];b=this.preflight(a);a=this.getR1AndR2(b);b=this.step0(b);b=this.step1(b,a.r1of);if(-1<this.arrStep1aExceptions.indexOf(b))return b;b=this.step2(b,a.r1of);b=this.step3(b,a.r1of,a.r2of);b=this.step4(b,a.r2of);return this.step5(b,a.r1of,a.r2of)}getR1AndR2(a){var b="";a.match(this.reR1Except)?b=a.replace(this.reR1Except,"$2"):a.match(this.reR1R2)&&(b=a.replace(this.reR1R2,"$1"));var c=a.length-b.length+1,d=b.replace(this.reR1R2,"$1"),e=d==b?"":d;return{r1:b,r2:e,
r1of:c,r2of:d==b?a.length+1:a.length-e.length+1}}wordIsShort(a,b){b=a.length<b;var c=new RegExp("^"+this.vowel+this.nonVowel+this.nonVowel+"*$");return!(!a.match(this.reEndsWithShortSyllable)&&!a.match(c)||!b)}preflight(a){return a.replace(/^'/,"").replace(/^y/,"Y").replace(new RegExp("("+this.vowel+")y"),"$1Y")}step0(a){return a.replace(/'(s(')?)?$/,"")}step1(a,b){var c=/(..)((ied)|(ies))$/,d=/((ied)|(ies))$/,e=new RegExp("(.*"+this.vowel+".+)s$"),g=/((us)|(ss))$/,k=/eed(ly)?$/,f=new RegExp("("+
this.vowel+".*)((ed)|(ing))(ly)?$"),h=/((at)|(bl)|(iz))$/,m=new RegExp("(.+"+this.nonVowel+")[Yy]$"),n=a;a.match(/sses$/)?n=a.replace(/sses$/,"ss"):a.match(c)?n=a.replace(d,"i"):a.match(d)?n=a.replace(d,"ie"):a.match(e)&&!a.match(g)&&(n=a.replace(e,"$1"));a=n;-1<this.arrStep1aExceptions.indexOf(n)?a=n:n.match(k)?(h=n.replace(k,"ee"),a=h.length+1>=b?h:n):n.match(f)&&(n=n.replace(f,"$1"),a=n.match(h)?n+"e":n.match(new RegExp(this.dbl+"$"))?n.replace(/.$/,""):this.wordIsShort(n,b)?n+"e":n);return a.match(m)?
a.replace(m,"$1i"):a}step2(a,b){for(var c=a,d=0;d<this.arrStep2Seq.length;d++)if(a.match(this.arrStep2Seq[d][0])){var e=a.replace(this.arrStep2Seq[d][1],"");if(e!=a){e.length+1>=b&&(c=a.replace(this.arrStep2Seq[d][1],this.arrStep2Seq[d][2]));break}}return c}step3(a,b,c){for(var d=a,e=0;e<this.arrStep3Seq.length;e++){var g=2==this.arrStep3Seq[e][0]?c:b,k=a.replace(this.arrStep3Seq[e][1],"");if(k!=a){k.length+1>=g&&(d=a.replace(this.arrStep3Seq[e][1],this.arrStep3Seq[e][2]));break}}return d}step4(a,
b){for(var c=a,d=0;d<this.arrStep4Seq.length;d++){var e=a.replace(this.arrStep4Seq[d][0],"");if(e!=a){e=a.replace(this.arrStep4Seq[d][1],"");e.length+1>=b&&(c=e);break}}return c}step5(a,b,c){var d=/(^[aeiouy][^aeiouy]$)|([^aeiouy][aeiouy][^aeiouywxY]$)/,e=a;if(a.match(/e$/)){var g=a.replace(/e$/,"");g.length+1>=c?e=g:g.length+1>=b&&!g.match(d)&&(e=g)}b=e;b==a&&b.match(/ll$/)&&(g=b.replace(/l$/,""),g.length+2>c&&(b=g));return b.replace(/Y/g,"y")}};